### PR TITLE
feat(mail): Add the Mozilla address to all emails.

### LINKED ISSUE #133: All emails need to contain our company name, address, and link to privacy policy
Mozilla
331 E. Evelyn Avenue Mountain View, CA 94041
`<a href="https://www.mozilla.org/privacy" style="color: #0095dd; text-decoration: none; font-family: sans-serif;">Mozilla Privacy Policy</a>`

### PR DESCRIPTION
**Pull request by shane-tomlinson**
fixes #133

### CODE REVIEW

**Comment by rfk** [comment]
thanks @shane-tomlinson;  looks like a rebase should fix the travis build failure

**Comment by shane-tomlinson** [comment]
This is ugly. @ryanfeeley - could I get your UI/UX eye on the case to make the email more visually appealing?

screen shot 2016-05-10 at 09 21 18

**Comment by shane-tomlinson** [comment]
@ryanfeeley - perhaps something a little more like this?

screen shot 2016-05-10 at 09 38 19

I have left aligned the "this is an automated email" text, and added a period. The spacing is slightly different. 

I shrunk the Mozilla text to 11px to match other "footer" text, as well as used the same color as the "this is an automated email" text. I have also made the spacing a bit less jarring.

An improvement, but I think an expert's eye (yours) is needed.

**Comment by ryanfeeley** [comment]
I propose no bold, all on one line and centered (same font style as "Alternatively")

Some examples from the wider wide:
screenshot 2016-05-10 10 41 40
screenshot 2016-05-10 10 41 32
screenshot 2016-05-10 10 41 26
screenshot 2016-05-10 10 39 57
screenshot 2016-05-10 10 39 38

**Comment by shane-tomlinson** [comment]
> I propose no bold, all on one line and centered (same font style as "Alternatively")

I like it, with the privacy policy link on the same line?

**Comment by ryanfeeley** [comment]
This should do?
Mozilla. 331 E Evelyn Ave, Mountain View, CA 94041. <a href=#">Privacy Policy</a>.

**Comment by shane-tomlinson** [comment]
@ryanfeeley - All the emails have been run through email on acid. Do you have creds to scan over them? I see a couple of emails with problems that seem unrelated to what we are doing here, e.g., the layout of "Re-verify your Firefox Account" needs to be updated. The account lockout feature is not yet enabled in production, so we can defer on that. Otherwise, I think the emails look good!

Lemme know what you think.

**Comment by shane-tomlinson** [comment]
@ryanfeeley has given this the r+ over Vidyo after a UX review of all the emails.

**Comment by vladikoff** [comment]
Yesss emails!

**Pull request merged**
