### PR TITLE
fix(l10n): make defaultLanguage configurable, and switch to "en" default

### PR DESCRIPTION
**Pull request by jrgm**
This adjusts the defaultLanguage from 'en-US' to 'en' and makes that sorta configurable. 
I don't particularly like the `config.i18n` part, since that's a detail from fxa-auth-server.

### CODE REVIEW

**Comment by jrgm** [comment]
Okay, took me a couple of takes, but this is simpler. 

Feel free to point out how wrong I am. r? dannycoates

**Comment by jrgm** [comment]
fxa-auth-server will need to add defaultLanguage here https://github.com/mozilla/fxa-auth-server/blob/master/mailer.js#L14

**Comment by jrgm** [comment]
cross ref https://github.com/mozilla/fxa-auth-mailer/issues/39

**Comment by rfk** [comment]
Thanks @jrgm.  I wonder if we could simplify this by assuming that `locales[0]` is the default language.  Maybe too much magic though.

Also /cc @zaach for reference, since I mentioned this in our 1:1 today.

**Comment by rfk** [comment]
> fxa-auth-server will need to add defaultLanguage

Like so?  https://github.com/mozilla/fxa-auth-server/pull/917

This LGTM, r+.

**Comment by jrgm** [comment]
> Like so? mozilla/fxa-auth-server#917

Yeah, that's what I meant. I was also going to add a test to call the translator with all the languages (and others).

**Comment by rfk** [comment]
Please, add as many tests as you like :-)

**Comment by dannycoates** [comment]
@jrgm yep LGTM r+

**Comment by jrgm** [comment]
Thanks.

**Pull request merged**
