### PR TITLE
chore(mail): Remove the verify_reminder_* templates

### LINKED ISSUE #144: verify_reminder_first.html and verify_reminder_second.html not used, should be removed from repo.
https://github.com/mozilla/fxa-auth-mailer/blob/master/templates/verify_reminder_first.html and 
https://github.com/mozilla/fxa-auth-mailer/blob/master/templates/verify_reminder_second.html are unused.

Instead [verification_reminder_first and verification_reminder_second](https://github.com/mozilla/fxa-auth-mailer/blob/0141a6d356f2b5712d27aec29bc62be43b272b73/templates/index.js#L59:L60) are used.

### PR DESCRIPTION
**Pull request by shane-tomlinson**
These templates are not actually referenced anywhere and are identical
to the verification_reminder_* variants.

fixes #144 

@vladikoff - r?

### CODE REVIEW

**Comment by vladikoff** [comment]
this is fixed by other reminder PRs

**Comment by shane-tomlinson** [comment]
> this is fixed by other reminder PRs

I don't see the files removed in https://github.com/mozilla/fxa-auth-mailer/pull/123, is there another PR that removes them?

**Comment by vladikoff** [comment]
Huh how strange, I didn't even have these files locally. Thanks 👍

**Comment by vladikoff** [comment]
Travis was fixed in the other PR

**Pull request merged**
