### PR TITLE
fix(coverage): Add script to enabled code coverage for local tests

### PR DESCRIPTION
**Pull request by vbudhram**
Noticed test coverage wasn't being reported for this. Uses the common coverage script.

### CODE REVIEW

**Comment by vbudhram** [comment]
@mozilla/fxa-devs r?

**Comment by vladikoff** [comment]
@vbudhram you probably want to enable coveralls for this as well, like: 

https://github.com/mozilla/fxa-auth-server/blob/master/.travis.yml#L53

**Comment by vladikoff** [comment]
@vbudhram I enabled it here: https://coveralls.io/github/mozilla/fxa-auth-mailer

**Comment by vbudhram** [comment]
@vladikoff Code coverage added, is there anything else I should add?

**Pull request merged**
