### PR TITLE
feat(metrics): track templates used in sent email

### LINKED ISSUE #130: Add ability to track # of email sent
We need a way to tell how many emails were sent by `mailer.js`

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #130

### CODE REVIEW

**Comment by vladikoff** [comment]
@rfk r? this should be enough to get an overview of sent email into Kibana

**Comment by vladikoff** [comment]
We would remove the `email` field from the dashboard and just use the template value.

**Comment by vladikoff** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1276709

**Comment by rfk** [comment]
LGTM, r+

> We would remove the email field from the dashboard and just use the template value.

IIUC this should happen automagically thanks to some PII filtering in heka.

**Pull request merged**
