### PR TITLE
feat(sms): implement status check

### PR DESCRIPTION
**Pull request by philbooth**
This is the auth mailer part of mozilla/fxa-auth-server#1646. It adds a method to check the balance of the nexmo account and indicate whether it's any good based on a threshold defined in config.

@mozilla/fxa-devs r?

### CODE REVIEW

**Comment by vladikoff** [comment]
@philbooth fxa-auth-mailer merged into fxa-auth-server, please try to file this PR against that.

**Comment by philbooth** [comment]
Thanks @vladikoff, if it's okay I'll still leave this open for review here in case anyone has time to give me feedback before I get back to it in the auth server.

**Comment by vladikoff** [comment]
👍

**Comment by philbooth** [comment]
Although actually, it's not like I can carry any r+ forward from here so maybe that's just wasting potential reviewer time. Re-closing.

**Pull request closed without merging**
