### PR TITLE
fix(schema): re-add schema html

### PR DESCRIPTION
**Pull request by johngruen**
@rfk let me run this through our testing service before merge

### CODE REVIEW

**Comment by rfk** [comment]
ack; r+ from me, merge when you're ready

**Comment by johngruen** [comment]
@vladikoff using the latest mozilla/fxa-local-dev + this https://gist.github.com/vladikoff/fbbd8ed20ae0b912dfd4 I am unable to run email tests locally because `node ./bin/key_server.js` throws an error.

**Comment by vladikoff** [comment]
Fixes #58

**Comment by johngruen** [comment]
@vladikoff for some reason this thing seems to break the img tag on outlook 2010. Could you fire off the test one more time?

**Pull request merged**
