### PR TITLE
chore(cleanup): Fixed some syntax errors reported by ESLint

### PR DESCRIPTION
**Pull request by pdehaan**
Addresses some of the basic ESLint style issues (quotes, spaces, semicolons) reported in #45.

### CODE REVIEW

**Comment by pdehaan** [comment]
Not sure if I broke the tests. I doubt it because I mostly added a space and changed quotes in the related files. Plus I notice that #42 PR was failing too with the same errors.

**Comment by jrgm** [comment]
Yeah, I'd actually picked this up in other tests this afternoon (scripts/e2e-email and fxa-auth-server tests). 
The reason is that the fxa-content-server-l10n localization for pt_BR changed their `Language:` header from `pt_BR` to `pt-BR`, which is counter to all the other country-specific localizations in fxa-content-server-l10n (es_AR,es_CL,nb_NO,sr_LATN,sv_SE,zh_CN,zh_TW) and the code in this repo is not prepared to deal with that (but shouldn't crash, of course). 

I'll file a bug in fxa-content-server-l10n asking for this change to be reversed if the change was incorrect. 
I'll look at a patch for this repo.

**Comment by jrgm** [comment]
The issue with crashing due to l10n content has been fixed, so ignore my earlier comment.

**Comment by pdehaan** [comment]
Closing.
This needs to be rebased, and @TDA did a better job with his #50 PR.

**Pull request closed without merging**
