### PR TITLE
fix(email): adjust sign-in subject to include Firefox instead of sync

### LINKED ISSUE #76: New subject 'New sign-in to Sync' should include 'Firefox Accounts' for better context
https://github.com/mozilla/fxa-auth-mailer/commit/e9a06ced3576b0c846826d23e675ed6de27d80d0#diff-3427c5e3d78d8d6550178ad46b9e0680L240

A user looking at their Inbox seeing 'New sign-in to Sync' would have no idea whether that is relevant to them without the word 'Firefox' to provide context.

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #76

### CODE REVIEW

**Comment by vladikoff** [comment]
@rfk r?

**Comment by rfk** [comment]
r+, but I'm not sure of the status of strings for the pending train so not merging right now

**Comment by vladikoff** [comment]
@zaach we just recently merged the strings, should we merge this now?

**Comment by vladikoff** [comment]
from mtg: Merge this when train-46 is in production

**Comment by vladikoff** [comment]
> from mtg: Merge this when train-46 is in production

It's live...

**Pull request merged**
