### PR TITLE
fix(travis): update Travis to MySql 5.6

### LINKED ISSUE #147: DB MySql changes incompatible with current Travis setup
Ref: https://travis-ci.org/mozilla/fxa-auth-mailer/jobs/128286555
image

### PR DESCRIPTION
**Pull request by vladikoff**
Fixes #147

### CODE REVIEW

**Comment by vladikoff** [comment]
@vbudhram @eoger r?

**Comment by vladikoff** [comment]
Same thing as we got here: https://github.com/mozilla/fxa-auth-server/commit/11beff9af9f4141d561cf5ebd9a82f3b2804dfc0

**Comment by eoger** [comment]
👍

**Comment by vbudhram** [comment]
LGTM 👍

**Comment by vladikoff** [comment]
Thanks Edouard and Vijay!

**Pull request merged**
