### PR TITLE
maybe fix #73

### LINKED ISSUE #73: Stretched "activate now" button when verification email viewed in Outlook
I was investigating our new mozsvc email-on-acid account, and sent a test verification email.  The really long "resume" token seemed to cause problems with line-breaking and resulted in a very wide "activate now" button in some desktop clients:

screen shot 2015-08-28 at 15 10 45

Similar artifacts showed up in a couple of other clients as well:

screen shot 2015-08-28 at 15 12 28

@ryanfeeley thoughts?

(I can also give you direct access to the test results, just ping me on IRC and I'll get you the account creds)

### PR DESCRIPTION
**Pull request by dannycoates**
untested

### CODE REVIEW

**Comment by rfk** [comment]
r+, assuming email-on-acid gives a good outcome

**Comment by dannycoates** [comment]
slightly better

**Comment by rfk** [comment]
Looks like this is strictly an improvement over the old version; there's a lot of *other* problems with the emails in outlook, but this indeed fixes the one identified in the linked bug.

**Comment by rfk** [comment]
@dannycoates please rebase with a more committal commit messages and merge at your convenience.

**Pull request merged**
